server:
  port: 8081

logging:
  level:
    org.slf4j.Logger: debug

mybatis:
  config: classpath:mybatis/config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

email.sender: jaeinlux@gmail.com

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  web:
    resources:
      static-locations: /WEB-INF/resources/
      add-mappings: true
    servlet:
      multipart:
        max-file-size: 100MB

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: mega_coffee
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: jaeinlux@gmail.com
    password: xibsowtsqulayura
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 613862669274-bh3iu76nbgaba138urlhv062kvc88aq2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 2449232841898281
            client-secret: c37ee3582e293fff62c5b1e2dc5f20f6
            scope:
              - email
              - public_profile
          naver:
            client-id: M9vl75r3pSW4d5JBMFoM
            client-secret: aNjSuLzBSH
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
